import os
Import('env')

prog = env.Library('gbemu', Glob("*.cpp"))

env.Alias("install", env.Install(os.path.join(env['PREFIX'], "include"), Glob("*.h")))
env.Alias("install", env.Install(os.path.join(env['PREFIX'], "lib"), prog))

